/* ==========================================================================
   DEFAULT PRODUCT CATALOG (products-data.js)
   Auto-generated seed data extracted from the original static product
   cards. This is only the STARTING catalog — product-store.js loads this
   once into localStorage; after that, the admin dashboard is the source
   of truth and everything (storefront + search + admin) reads from
   localStorage instead of this file.
   ========================================================================== */

const DEFAULT_PRODUCTS = [
  {
    "id": "p1",
    "name": "Hirono X Kodak Click Bear Plush Doll Pandant",
    "series": "Kodak Click Bear",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 39.99,
    "image": "images/hirono-plush-doll/hirono-kodak-click-bear-plush-doll-pandant.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": true,
    "visible": true
  },
  {
    "id": "p2",
    "name": "Hirono The Other One - Dreaming (Secret)",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 74.99,
    "image": "images/hirono-figures/Hirono-the-other-one/Dreaming-(Secret).webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": true,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p3",
    "name": "Hirono Mist Walker - Jacquard Blanket",
    "series": "Mist Walker",
    "category": "Accessories",
    "type": "Accessory",
    "price": 59.99,
    "image": "images/hirono-accessories/hirono-mist-walker-jacquard-blanket.webp",
    "isNew": true,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p4",
    "name": "Hirono Le Petit Prince - The Little Prince",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-little-prince.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p5",
    "name": "Hirono Behind Time",
    "series": "Behind Time",
    "category": "Figures",
    "type": "Figure",
    "price": 49.99,
    "image": "images/hirono-figures/hirono-behind-time-figure-new-arrival.webp",
    "isNew": true,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p6",
    "name": "Hirono Echo 3D Ceramic Cup",
    "series": "Hirono Echo",
    "category": "Accessories",
    "type": "Accessory",
    "price": 44.99,
    "image": "images/hirono-accessories/hirono-echo-3d-ceramic-cup.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p7",
    "name": "Hirono Ceramic Feather",
    "series": "Ceramic",
    "category": "Figures",
    "type": "Figure",
    "price": 156.99,
    "image": "images/hirono-figures/hirono-ceramic-feather-figurine.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p8",
    "name": "Hirono Road Journal - Lost in the Night",
    "series": "Road Jounal",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 35.99,
    "image": "images/hirono-plush-doll/Hirono-Road-Journal/lost-in-the-night.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p9",
    "name": "Hirono Chucky Figurine",
    "series": "Chucky",
    "category": "Figures",
    "type": "Figure",
    "price": 149.99,
    "image": "images/hirono-figures/hirono-chucky-figurine.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p10",
    "name": "Hirono Head Silence",
    "series": "Dead Silence",
    "category": "Figures",
    "type": "Figure",
    "price": 43.99,
    "image": "images/hirono-figures/hirono-dead-silence-figure.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p11",
    "name": "Hirono Bear VinyI Plush Doll",
    "series": "VinyI",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 114.99,
    "image": "images/hirono-plush-doll/hirono-bear-vinyi-plush-doll.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p12",
    "name": "Hirono Gap Glimmer Wanderer",
    "series": "Mist Walker",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 29.99,
    "image": "images/hirono-plush-doll/Hirono-mist-walker/the-gap-glimmer-wanderer.webp",
    "isNew": true,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p13",
    "name": "Hirono Le Petit Prince - The Businessman",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-businessman.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p14",
    "name": "Hirono The Little Mischief - Birdman",
    "series": "The Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/birdman.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p15",
    "name": "Hirono Road Journal - Hishway Imprint (Secret)",
    "series": "Road Journal",
    "category": "Figures",
    "type": "Figure",
    "price": 59.99,
    "image": "images/hirono-plush-doll/Hirono-Road-Journal/highway-imprint(secret).webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": true,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p16",
    "name": "Hirono Mime - Blind",
    "series": "Mime",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Mime/blind.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p17",
    "name": "Hirono Monster Carnival - Creepy Clown",
    "series": "Monster Carnival",
    "category": "Figures",
    "type": "Figure",
    "price": 20.99,
    "image": "images/hirono-figures/Hirono-Monster-Carnival/creepy-clown.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p18",
    "name": "Hirono Bear Plush Hand Puppet",
    "series": "Plush Hand Puppet",
    "category": "Accessories",
    "type": "Accessory",
    "price": 34.99,
    "image": "images/hirono-accessories/hirono-bear-plush-hand-puppet.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p19",
    "name": "Hirono Reshape - Burst",
    "series": "Reshape",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Reshape/Burst.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p20",
    "name": "Hirono Shelter - Alien",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Alien.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p21",
    "name": "Hirono Tamed Wildgrass - Boiling Frog",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/boiling-frog.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p22",
    "name": "Hirono Le Petit Prince - The Geographer",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-geographer.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p23",
    "name": "Hirono The Other One - Amnesia",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/Amnesia.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p24",
    "name": "Hirono Little Hare Plush Doll Pendant - Regular Version",
    "series": "Little Hare",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 49.99,
    "image": "images/hirono-plush-doll/hirono-little-hare-plush-doll-pendant.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p25",
    "name": "Hirono Mist Walker - The Primodial Grace",
    "series": "Mist Walker",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 29.99,
    "image": "images/hirono-plush-doll/Hirono-mist-walker/the-primodial-grace.webp",
    "isNew": true,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p26",
    "name": "Hirono Road Jounal - City Dust Afloat",
    "series": "Road Jounal",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 35.99,
    "image": "images/hirono-plush-doll/Hirono-Road-Journal/city-dust-afloat.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p27",
    "name": "Hirono Little Hare Plush Doll Pendant - Special Version",
    "series": "Little Hare",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 49.99,
    "image": "images/hirono-plush-doll/hirono-little-hare-plush-doll-pendant-special-version.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p28",
    "name": "Hirono Living Wild Fight For Joy",
    "series": "Living Wild Fight For Joy",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 50.99,
    "image": "images/hirono-plush-doll/hirono-living-wild-fight-for-joy-plush-doll.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p29",
    "name": "Hirono Ploar Symbiosis",
    "series": "Ploar Symbiosis",
    "category": "Figures",
    "type": "Figure",
    "price": 59.99,
    "image": "images/hirono-figures/hirono-ploar-symbiosis-figure.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p30",
    "name": "Hirono Reshape Figurine",
    "series": "Reshape",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-reshape-figurine.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p31",
    "name": "Hirono Monster's Carnival - The Disembodied (Secret)",
    "series": "Monster's Carnival",
    "category": "Figures",
    "type": "Figure",
    "price": 31.99,
    "image": "images/hirono-figures/Hirono-Monster-Carnival/the-disembodied(secret).webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": true,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p32",
    "name": "Hirono Mist Walker - The Soul Corroder",
    "series": "Mist Walker",
    "category": "Figures",
    "type": "Figure",
    "price": 29.99,
    "image": "images/hirono-plush-doll/Hirono-mist-walker/the-soul-corroder.webp",
    "isNew": true,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p33",
    "name": "Hirono Dino Plush Hand Puppet",
    "series": "Plush Hand Puppet",
    "category": "Accessories",
    "type": "Accessory",
    "price": 34.99,
    "image": "images/hirono-accessories/hirono-dino-plush-hand-puppet.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p34",
    "name": "Hirono Echo Paper Shelled Mug",
    "series": "Hirono Echo",
    "category": "Accessories",
    "type": "Accessory",
    "price": 32.99,
    "image": "images/hirono-accessories/hirono-echo-paper-shelled-mug.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p35",
    "name": "Hirono Echo Passport Bag",
    "series": "Hirono Echo",
    "category": "Accessories",
    "type": "Accessory",
    "price": 25.99,
    "image": "images/hirono-accessories/hirono-echo-passport-bag.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p36",
    "name": "Hirono Road Journal - Insulated Tumbler",
    "series": "Road Journal",
    "category": "Accessories",
    "type": "Accessory",
    "price": 45.99,
    "image": "images/hirono-accessories/hirono-road-journal-insulated-tumbler.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p37",
    "name": "Hirono Simper",
    "series": "Simper",
    "category": "Figures",
    "type": "Figure",
    "price": 37.99,
    "image": "images/hirono-figures/hirono-simper-figure.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p38",
    "name": "Hirono Road Journal - FrostFall Hour",
    "series": "Road Journal",
    "category": "Figures",
    "type": "Figure",
    "price": 35.99,
    "image": "images/hirono-plush-doll/Hirono-Road-Journal/frostfall-hour.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p39",
    "name": "Hirono Search For Aliens Figurine",
    "series": "Search For Aliens",
    "category": "Figures",
    "type": "Figure",
    "price": 169.99,
    "image": "images/hirono-figures/hirono-search-for-aliens-figureine.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p40",
    "name": "Hirono Road Journal - Knitted Phone Case",
    "series": "Road Journal",
    "category": "Accessories",
    "type": "Accessory",
    "price": 42.99,
    "image": "images/hirono-accessories/hirono-road-journal-knitted-phone-case.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p41",
    "name": "Hirono Le Petit Prince - The Conceited Man",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-conceited-man.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p42",
    "name": "Hirono Leah Dou In The Air",
    "series": "Leah Dou",
    "category": "Figures",
    "type": "Figure",
    "price": 129.99,
    "image": "images/hirono-figures/hirono-leah-dou-in-the-air-figure-new-arrival.webp",
    "isNew": true,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p43",
    "name": "Hirono Little Mischief - Destroyer",
    "series": "Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/destroyer.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p44",
    "name": "Hirono Mime - Delivery",
    "series": "Mime",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Mime/devilry.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p45",
    "name": "Hirono Monster's Carnival - Doctor Beak",
    "series": "Monster's Carnival",
    "category": "Figures",
    "type": "Figure",
    "price": 20.99,
    "image": "images/hirono-figures/Hirono-Monster-Carnival/doctor-beak.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p46",
    "name": "Hirono Reshape - Costume",
    "series": "Reshape",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Reshape/Costume.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p47",
    "name": "Hirono Echo Knight",
    "series": "Hirono Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-echo/knight.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p48",
    "name": "Hirono Shelter - Bird Cage",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Birdcage.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p49",
    "name": "Hirono Tamed Wildgrass - Boundary (Secret)",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 31.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/boundary(secret).webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": true,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p50",
    "name": "Hirono The Other One - Being Alive",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/Being-Alive.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p51",
    "name": "Hirono Backlit Messenger",
    "series": "Mist Walker",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 29.99,
    "image": "images/hirono-plush-doll/Hirono-mist-walker/the-backlit-messenger.webp",
    "isNew": true,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p52",
    "name": "Hirono Echo - Back Off",
    "series": "Hirono Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-echo/back-off.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p53",
    "name": "Hirono Echo - Breakout Plan",
    "series": "Hirono Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-echo/breakout-plan.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p54",
    "name": "Hirono Tamed Wildgrass - Sisyphean Work",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/Sisyphean-Work.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p55",
    "name": "Hirono Le Petit Prince - The Fox",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-fox.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p56",
    "name": "Hirono Little Mischief - Float",
    "series": "Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/float.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p57",
    "name": "Hirono Mist Walker - The Tempered Aegis (Secret)",
    "series": "Mist Walker",
    "category": "Figures",
    "type": "Figure",
    "price": 86.99,
    "image": "images/hirono-plush-doll/Hirono-mist-walker/the-tempered-aegis(secret).webp",
    "isNew": true,
    "isPopular": false,
    "isLimited": true,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p58",
    "name": "Hirono Mime - Fool",
    "series": "Mime",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Mime/fool.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p59",
    "name": "Hirono Monster's Carnival - Grim Reaper",
    "series": "Monster's Carnival",
    "category": "Figures",
    "type": "Figure",
    "price": 20.99,
    "image": "images/hirono-figures/Hirono-Monster-Carnival/grim-reaper.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p60",
    "name": "Hirono Reshape - Drownling",
    "series": "Reshape",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Reshape/Drownling.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p61",
    "name": "Hirono Shelter - Birdy",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Birdy.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p62",
    "name": "Hirono Snoopy Figurine",
    "series": "Snoopy",
    "category": "Figures",
    "type": "Figure",
    "price": 43.99,
    "image": "images/hirono-figures/hirono-snoopy-figure.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p63",
    "name": "Hirono Monster's Carnival - Killer Bunny",
    "series": "Monster's Carnival",
    "category": "Figures",
    "type": "Figure",
    "price": 20.99,
    "image": "images/hirono-figures/Hirono-Monster-Carnival/killer-bunny.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p64",
    "name": "Hirono The Pianist Figurine",
    "series": "The Pianist",
    "category": "Figures",
    "type": "Figure",
    "price": 53.99,
    "image": "images/hirono-figures/hirono-the-pianist-figure.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p65",
    "name": "Hirono Tamed Wildgrass - Caged Bird",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/caged-bird.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p66",
    "name": "Hirono Road Journal - Grey Gravel",
    "series": "Road Journal",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 35.99,
    "image": "images/hirono-plush-doll/Hirono-Road-Journal/grey-gravel.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p67",
    "name": "Hirono The Other One - Cuckoo",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/Cuckoo.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p68",
    "name": "Hirono Echo - Phone Case",
    "series": "Hirono Echo",
    "category": "Accessories",
    "type": "Accessory",
    "price": 33.99,
    "image": "images/hirono-accessories/hirono-echo-phone-case.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p69",
    "name": "Hirono Echo - Table Lamp",
    "series": "Hirono Echo",
    "category": "Accessories",
    "type": "Accessory",
    "price": 73.99,
    "image": "images/hirono-accessories/hirono-echo-table-lamp.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p70",
    "name": "Hirono Le Petit Prince - The Little Prince (Secret)",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 41.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-little-prince(secret).webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": true,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p71",
    "name": "Hirono Stefanie Sun Aut Nihilo Figurine",
    "series": "Stefanie",
    "category": "Figures",
    "type": "Figure",
    "price": 59.99,
    "image": "images/hirono-figures/hirono-stefanie-sun-aut-nihilo-figure.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p72",
    "name": "Hirono Echo - Day Dreaming",
    "series": "Hirono Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-echo/daydreaming.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p73",
    "name": "Hirono Shelter - Candle Holder",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Candleholder.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p74",
    "name": "Hirono Stefanie Sun Weather With You",
    "series": "Stefanie",
    "category": "Figures",
    "type": "Figure",
    "price": 149.99,
    "image": "images/hirono-figures/hirono-stefanie-sun-weather-with-you-figure.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p75",
    "name": "Hirono Mist Walker - The Unfallen Wing",
    "series": "Mist Walker",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 29.99,
    "image": "images/hirono-plush-doll/Hirono-mist-walker/the-unfallen-wing.webp",
    "isNew": true,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p76",
    "name": "Hirono Tamed Wildgrass - Camping",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/Camping.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p77",
    "name": "Hirono Echo - Eaten",
    "series": "Hirono Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-echo/eaten.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p78",
    "name": "Hirono Mime - Silent (Secret)",
    "series": "Mime",
    "category": "Figures",
    "type": "Figure",
    "price": 86.99,
    "image": "images/hirono-figures/Hirono-Mime/secret.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": true,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p79",
    "name": "Hirono Road Journal - Into Fogwild",
    "series": "Road Journal",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 35.99,
    "image": "images/hirono-plush-doll/Hirono-Road-Journal/into-fogwild.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p80",
    "name": "Hirono Le Petit Prince - The King",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-king.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p81",
    "name": "Hirono Echo - Never Glowing Up (Secret)",
    "series": "Hirono Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 31.99,
    "image": "images/hirono-figures/hirono-echo/never-glowing-up(secret).webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": true,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p82",
    "name": "Hirono The Other One - Raving",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/Raving.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p83",
    "name": "Hirono Tamed Wildgrass - City Escape",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/city-escape.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p84",
    "name": "Hirono Little Mischief - Loose Fish",
    "series": "Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/loose-fish.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p85",
    "name": "Hirono Mist Walker - The Wingless Follower",
    "series": "Mist Walker",
    "category": "Plush Dolls",
    "type": "Plush Doll",
    "price": 29.99,
    "image": "images/hirono-plush-doll/Hirono-mist-walker/the-wingless-follower.webp",
    "isNew": true,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p86",
    "name": "Hirono Mime - Guardian",
    "series": "Mime",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Mime/guardian.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p87",
    "name": "Hirono Reshape - Fading",
    "series": "Reshape",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Reshape/Fading.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p88",
    "name": "Hirono Le Petit Prince - The Pilot (Secret)",
    "series": "Hirono Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 26.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-pilot(secret).webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": true,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p89",
    "name": "Hirono Shelter - Cabin",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Cabin.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p90",
    "name": "Hirono Le Petit Prince - The Rose",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-rose.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p91",
    "name": "Hirono Echo - Get Lucky",
    "series": "Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-echo/get-lucky.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p92",
    "name": "Hirono Monster's Carnival - Figure Scene Prop",
    "series": "Monster's Carnival",
    "category": "Accessories",
    "type": "Accessory",
    "price": 7.99,
    "image": "images/hirono-accessories/hirono-monster-carnival-figure-scene-prop.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p93",
    "name": "Hirono Echo - Hiding Behind You",
    "series": "Hirono Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-echo/hiding-behind-you.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p94",
    "name": "Hirono Le Petit Prince - The Lamp Lighter",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 73.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-lamplighter.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p95",
    "name": "Hirono Road Journal - Patchwork Phone Case",
    "series": "Road Journal",
    "category": "Accessories",
    "type": "Accessory",
    "price": 42.99,
    "image": "images/hirono-accessories/hirono-road-journal-patchwork-phone-case.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p96",
    "name": "Hirono Little Mischief - Manacle",
    "series": "Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/manacle.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p97",
    "name": "Hirono Road Journal - Woven Woods",
    "series": "Road Journal",
    "category": "Figures",
    "type": "Figure",
    "price": 35.99,
    "image": "images/hirono-plush-doll/Hirono-Road-Journal/woven-woods.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p98",
    "name": "Hirono The UFO Cashier - Journey To The West",
    "series": "UFO Cashier",
    "category": "Figures",
    "type": "Figure",
    "price": 37.99,
    "image": "images/hirono-figures/hirono-the-ufo-cashier-journey-to-the-west-figure.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p99",
    "name": "Hirono Little Mischief - Rag Picker",
    "series": "Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/ragpicker.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p100",
    "name": "Hirono The Other One - Marionette",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/Marionette.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p101",
    "name": "Hirono Reshape - Healing",
    "series": "Reshape",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Reshape/Healing.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p102",
    "name": "Hirono Little Mischief - Persona",
    "series": "Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/persona.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p103",
    "name": "Hirono Echo - Journey In The Rain",
    "series": "Hirino Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-echo/journey-in-the-rain.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p104",
    "name": "Hirono Little Mischief - Pretender",
    "series": "Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/pretender.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p105",
    "name": "Hirono Mime - Seeker",
    "series": "Mime",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Mime/seeker.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p106",
    "name": "Hirono Monster's Carnival - Vampire",
    "series": "Monster's Carnival",
    "category": "Figures",
    "type": "Figure",
    "price": 20.99,
    "image": "images/hirono-figures/Hirono-Monster-Carnival/vampire.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p107",
    "name": "Hirono Reshape - Paradise Lost",
    "series": "Reshape",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Reshape/Paradise-Lost.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p108",
    "name": "Hirono Shelter - Cicus",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Cicus.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p109",
    "name": "Hirono Tamed Wildgrass - Digital Bind",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/digital-bind.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p110",
    "name": "Hirono The Other One - Nowhere Safe",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/Nowhere-Safe.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p111",
    "name": "Hirono Echo - Peice Of Memory",
    "series": "Hirono Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-echo/peice-of-memory.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p112",
    "name": "Hirono Le Petit Prince - The Merchant",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images//hirono-figures/Hirono-LePtitPrince/the-merchant.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p113",
    "name": "Hirono Little Mischief - Protector",
    "series": "Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/protector.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p114",
    "name": "Hirono Mime - Unspoken",
    "series": "Mime",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Mime/unspoken.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p115",
    "name": "Hirono Monster's Carnival - Zombie",
    "series": "Monster's Carnival",
    "category": "Figures",
    "type": "Figure",
    "price": 20.99,
    "image": "images/hirono-figures/Hirono-Monster-Carnival/zombie.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p116",
    "name": "Hirono Reshape - Parasite",
    "series": "Reshape",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Reshape/Parasite.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p117",
    "name": "Hirono Reshape - Voyage",
    "series": "Reshape",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Reshape/Voyage.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p118",
    "name": "Hirono Rashape - Wood Caving",
    "series": "Reshape",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Reshape/Woodcaving.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p119",
    "name": "Hirono Echo - Soul Connection",
    "series": "Hirono Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-echo/soul-connection.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p120",
    "name": "Hirono Shelter - Fort",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Fort.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p121",
    "name": "Hirono Tamed Wildgrass - Fated",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/Fated.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p122",
    "name": "Hirono The Other One - Staring",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/Staring.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p123",
    "name": "Hirono Echo - Staying Up",
    "series": "Hirono Echo",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/hirono-echo/staying-up.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p124",
    "name": "Hirono Le Petit Prince - The Snake",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-snake.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p125",
    "name": "Hirono Shelter - Mental Clock",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Mentel-Clock.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p126",
    "name": "Hirono Tamed Wildgrass - Full Time",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/Full-Time.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p127",
    "name": "Hirono The Other One - The Crow",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/The-Crow.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p128",
    "name": "Hirono Little Mischief - Robot",
    "series": "Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/robot.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p129",
    "name": "Hirono Shelter - Poet",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Poet.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p130",
    "name": "Hirono Le Petit Prince - The Switch Man",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-switchman.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p131",
    "name": "Hirono Little Mischief - The Aviator",
    "series": "Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/the-aviator.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p132",
    "name": "Hirono Shelter - Stuffed Bear (Secret)",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 47.99,
    "image": "images/hirono-figures/Hirono-Shelter/StuffBear.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": true,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p133",
    "name": "Hirono Tamed Wildgrass - Live Under Receipt",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/Live-Under-Receipt.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p134",
    "name": "Hirono The Other One - The Fox",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/the-fox.webp",
    "isNew": false,
    "isPopular": true,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p135",
    "name": "Hirono Le Petit Prince - The Tippler",
    "series": "Le Petit Prince",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-LePtitPrince/the-tippler.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p136",
    "name": "Hirono Little Mischief - Unknown Journey (Secret)",
    "series": "Little Mischief",
    "category": "Figures",
    "type": "Figure",
    "price": 116.99,
    "image": "images/hirono-figures/Hirono-Little-Mischief-Series/unknown-journey(secret).webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p137",
    "name": "Hirono Shelter - Sunny Doll",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Sunny-Doll.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p138",
    "name": "Hirono Tamed Wildgrass - Overload",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/Overload.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p139",
    "name": "Hirono The Other One - The Ghost",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/The-Ghost.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p140",
    "name": "Hirono Shelter - Traffic Cone",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Traffic-Cone.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p141",
    "name": "Hirono The Other One - The Monster",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/The-monster.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p142",
    "name": "Hirono Tamed Wildgrass - Self Anchored",
    "series": "Tamed Wildgrass",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Tamed-Wildgrass/Self-Anchored.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p143",
    "name": "Hirono Shelter - Warrior",
    "series": "Shelter",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-Shelter/Warrior.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  },
  {
    "id": "p144",
    "name": "Hirono The Other One - Vagrancy",
    "series": "The Other One",
    "category": "Figures",
    "type": "Figure",
    "price": 19.99,
    "image": "images/hirono-figures/Hirono-the-other-one/Vagrancy.webp",
    "isNew": false,
    "isPopular": false,
    "isLimited": false,
    "isComingSoon": false,
    "visible": true
  }
];
